fullnameOverride: "shared-resources"
replicaCount: 1

global:
  nodeSelector: {}

  tolerations: []

  affinity: {}

ingress:
  enabled: true
  className: "alb"
  annotations: 
    alb.ingress.kubernetes.io/scheme: internet-facting
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{\"HTTP\": 80}, {\"HTTPS\": 443}]''
    alb.ingress.kubernetes.io/ssl-redirect: 443
  hosts:
    - host: demo.projects.tentech.vok.today
      paths:
        - path: /books
          pathType: Prefix
          backend:
            service:
              name: books
              port:
                number: 8002
        - path: /order
          pathType: Prefix
          backend:
            service:
              name: order
              port:
                number: 8001
        - path: /auth
          pathType: Prefix
          backend:
            service:
              name: auth
              port:
                number: 8000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ui
              port:
                number: 80
  tls: []
#  - secretName: chart-example-tls
#    hosts:
#      - chart-example.local
