apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bookapp-external-secret
spec:
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore 
  target:
    name: bookapp-secret
    template:
      data:
        .env: |
          POSTGRES_USER={{ .data.rds_username}}
          POSTGRES_PASSWORD={{ .data.rds_password}}
          POSTGRES_DB={{ .data.rds_db_name}}
          POSTGRES_HOST={{ .data.rds_endpoint}}
          DATABASE_URL=postgresql://{{ .data.rds_username}}:{{ .data.rds_password}}@{{ .data.rds_endpoint}}/{{ .data.rds_db_name}}
          POSTGRES_PORT=5432
          REDIS_HOST={{ .data.redis_host}}
          RABBITMQ_HOST={{ .data.rabbitmq_host}}
          RABBITMQ_USERNAME={{ .data.rabbitmq_username}}
          RABBITMQ_PASSWORD={{ .data.rabbitmq_password}}      
  data:
    - secretKey: rds_username
      remoteRef:
        key: /rds/username
    - secretKey: rds_password
      remoteRef:
        key: /rds/password
    - secretKey: rds_db_name
      remoteRef:
        key: /rds/db_name
    - secretKey: rds_endpoint
      remoteRef:
        key: /rds/endpoint
    - secretKey: redis_host
      remoteRef:
        key: /redis/endpoint
    - secretKey: rabbitmq_host
      remoteRef:
        key: /rabbitmq/endpoint
    - secretKey: rabbitmq_username
      remoteRef:
        key: /rabbitmq/username
    - secretKey: rabbitmq_password
      remoteRef:
        key: /rabbitmq/password
