apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets