# Specific settings for each sub-chart
tntk-web:
  fullnameOverride: "web"
  replicaCount: 1
  image:
    repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/tntk-web
    pullPolicy: IfNotPresent
    tag: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 80
  resources: {}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  configmapData:
    PORT: "80"
  ingress:
    enabled: true
    className: "alb"
    annotations: {}
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

tntk-orders:
  fullnameOverride: "orders"
  replicaCount: 1
  image:
    repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/tntk-orders
    pullPolicy: IfNotPresent
    tag: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 80
  resources: {}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  postgresql:
    host: postgres
    port: 5432
    username: postgres
    password: postgres
    database: postgres
  redis:
    host: redis
  rabbitmq:
    host: rabbitmq

tntk-auth:
  fullnameOverride: "auth"
  replicaCount: 1
  image:
    repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/tntk-auth
    pullPolicy: IfNotPresent
    tag: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 8002
  resources: {}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

tntk-products:
  fullnameOverride: "products"
  replicaCount: 1
  image:
    repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/tntk-products
    pullPolicy: IfNotPresent
    tag: ""
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 8000
  resources: {}
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}